version: 0.2

phases:
  pre_build:
    commands:
      # Simplified ECR login
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264136175.dkr.ecr.us-east-1.amazonaws.com
      
      # Create minimal .env
      - echo "APP_ENV=production" >> .env
      - echo "APP_DEBUG=false" >> .env
      - echo "DB_CONNECTION=mysql" >> .env

  build:
    commands:
      - docker build -t laravel:latest .
      - docker tag laravel:latest 058264136175.dkr.ecr.us-east-1.amazonaws.com/laravel:latest

  post_build:
    commands:
      - docker push 058264136175.dkr.ecr.us-east-1.amazonaws.com/laravel:latest
      - echo '[{"name":"laravel","imageUri":"058264136175.dkr.ecr.us-east-1.amazonaws.com/laravel:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - 'imagedefinitions.json'
