version: 0.2

phases:
  pre_build:
    commands:
      # Simplified ECR login
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 407927038386.dkr.ecr.us-east-1.amazonaws.com
      
      # Create minimal .env
      - echo "APP_ENV=production" > .env
      - echo "APP_DEBUG=false" >> .env

  build:
    commands:
      - docker build -t demo-app .
      - docker tag demo-app:latest 407927038386.dkr.ecr.us-east-1.amazonaws.com/demo-app:latest

  post_build:
    commands:
      - docker push 407927038386.dkr.ecr.us-east-1.amazonaws.com/demo-app:latest
      - echo '[{"name":"demo-app","imageUri":"407927038386.dkr.ecr.us-east-1.amazonaws.com/demo-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - 'imagedefinitions.json'
